experiment_single:
  # Experiment Configuration
  description: "eval_2-1-b-01"
  label: "F-Opt-1$_{}^{+}$"
  num_eval_iters: 20
  # Network Configuration
  network_params:
    num_neurons: 50
    env_length: 200
#    T: 2
#    init_value: 0.01
    f: 0.95
    nmax: 50
    nmed: 48
    nmin: 50
#    I: 0.1
#    J0: -0.02
#    J1: 0.05
#    noise_type: 'gaussian'
#    I_std: 0.02
#    I: 0
#    J0: -0.3
#    J1: 0.35
#    interaction_length: 0.05
#    I: 0Updated optimization run of V-MSMF model
#    J0: -0.42
#    J1: 0.55
# Best weights from opt-02
#    f: 0.45
#    nmin: 11
#    nmed: 10
#    nmax: 9
#    J1: 0.22
#    J0: -0.04
# Best weights from opt-04
#    J1: 0.04
#    J0: -0.1
#    Best weights from opt-05
#    J1: 0.2
#    J0: -0.04
#    f: 0.4
#    nmin: 11
#    nmed: 10
#    nmax: 9
#    interaction_length: 0.01
#    interaction_length_factor: 3
#    Iloc: 0.0
#    disc_step: 1.0
    I: 0.0
    J1: 0.0
    J0: 0.0
#    interaction_length: 0.05
#    prob_dead_neurons: 0.3
#    pos_input_suppression_start: 240.0
#    pos_input_suppression_end: 260.0
#    f: 0.4
#    nmin: 11
#    nmed: 10
#    nmax: 9
    expected_mean_field_activity: 0.015
    mean_field_activity_remove_background: True
#    replace_neuron_attractor: False
  # Evaluation Configuration
  global_metrics:
    pos_error_mean: [ mean, min, max, std, median ]
    pos_error_std: [ mean, min, max, std, median ]
    pos_error_min: [ mean]
    pos_error_max: [ mean]
    pos_error_num_cat: [ mean, median ]
    mean_field_activity: [ mean, min, max, std, median ]
    perc_correct_fields: [ mean, min, max, std, median ]
    avg_num_fields_per_neuron: [ mean, std]
    avg_num_fields_active_per_neuron: [ mean, std ]
    avg_accum_field_coverage_per_neuron: [ mean, std ]
#    num_fields_total: [ mean, std]
#    num_fields_active: [ mean, std]
    activity_false_positives_num: [ mean, min, max, std, median ]
    activity_false_negatives_num: [ mean, min, max, std, median ]
    perc_unique_field_combinations: [ mean, min, max, std, median ]
    weighted_avg_activity: [ mean, std, median ]
  plots:
    neuron_activity_static: True
experiment_a:
  # Experiment Configuration
  description: "Proportion of neurons sampled for each attractor"
  num_eval_iters: 10
  # Parameter Configuration
  param_name: f
  param_eval_range_min: 0.02
  param_eval_range_max: 1.02
  param_eval_range_step: 0.02
  # Network Configuration
  network_params:
    num_neurons: 500
    env_length: 200
    init_value: 0.01
    prob_dead_neurons: 0.0
  # Evaluation Configuration
  metrics:
    - pos_error_mean
    - pos_error_std
  plots:
    pos_error_mean: True
    pos_error_std: True
experiment_b:
  # Experiment Configuration
  description: "Total number of neurons"
  num_eval_iters: 10
  # Parameter Configuration
  param_name: num_neurons
  param_eval_range_min: 50
  param_eval_range_max: 1050
  param_eval_range_step: 50
  # Network Configuration
  network_params:
    f: 0.3
    num_neurons: 50
    env_length: 200
    init_value: 0.01
    prob_dead_neurons: 0.0
  # Evaluation Configuration
  global_metrics:
    pos_error_mean: [ mean, min, max, std, median ]
    pos_error_std: [ mean, min, max, std, median ]
    pos_error_min: [ mean, min, max, std ]
    pos_error_max: [ mean, min, max, std ]
    mean_field_activity: [mean]
    perc_correct_fields: [mean]
    avg_num_fields_per_neuron: [ mean, min, max, std, median ]
    num_fields_total: [ mean, min, max, std, median ]
  plots:
    pos_error_mean: True
    pos_error_std: True
experiment_c:
  # Experiment Configuration
  description: "Test"
  num_eval_iters: 5
  # Parameter Configuration
  param_name: num_neurons
  param_eval_range_min: 50
  param_eval_range_max: 150
  param_eval_range_step: 50
  # Network Configuration
  network_params:
    f: 0.3
    num_neurons: 50
    env_length: 200
    init_value: 0.01
    prob_dead_neurons: 0.0
  # Evaluation Configuration
  global_metrics:
    pos_error_mean: [ mean, min, max, std, median ]
    pos_error_std: [ mean, min, max, std, median ]
    pos_error_min: [ mean, min, max, std ]
    pos_error_max: [ mean, min, max, std ]
    mean_field_activity: [mean]
    perc_correct_fields: [mean]
    avg_num_fields_per_neuron: [ mean, min, max, std, median ]
    num_fields_total: [ mean, min, max, std, median ]
  plots:
    pos_error_mean: True
    pos_error_std: True
experiment_2-4-a:
  # Experiment Configuration
  description: "Median error increase relative to number of fields"
  label: "opt-5_opt-exp-15_num-fields-low"
  num_eval_iters: 20
  # Parameter Configuration
  param_name: prob_dead_neurons
  param_eval_range_min: 0.0
  param_eval_range_max: 1.00
  param_eval_range_step: 0.05
  network_params:
    env_length: 200
    num_neurons: 50
#    init_value: 0.01
    I: 0.0  # constant background input
    J1: 0.0  # maximum excitatory connection between neurons
    J0: 0.0  # maximum inhibitory connection between neurons
#    Iloc: 0.05  # amplitude of a place-specific input
    f: 0.4
    nmin: 50
    nmed: 22
    nmax: 40
#    disc_step: 0.5
    expected_mean_field_activity: 0.015
    mean_field_activity_remove_background: True
#    replace_neuron_attractor: False
  # Evaluation Configuration
  global_metrics:
    pos_error_mean: [ mean, min, max, std, median ]
    pos_error_std: [ mean, min, max, std, median ]
    pos_error_min: [ mean]
    pos_error_max: [ mean]
    pos_error_num_cat: [ mean, median ]
    mean_field_activity: [ mean, min, max, std, median ]
    perc_correct_fields: [ mean, min, max, std, median ]
    avg_num_fields_per_neuron: [ mean, std]
    avg_num_fields_active_per_neuron: [ mean, std ]
    avg_accum_field_coverage_per_neuron: [ mean, std ]
#    num_fields_total: [ mean, std]
#    num_fields_active: [ mean, std]
    activity_false_positives_num: [ mean, min, max, std, median ]
    activity_false_negatives_num: [ mean, min, max, std, median ]
    perc_unique_field_combinations: [ mean, min, max, std, median ]
    weighted_avg_activity: [ mean, std, median ]
  plots:
    pos_error_mean: True
    pos_error_std: False
experiment_3-2-a:
  # Experiment Configuration
  description: "Median error increase relative to number of fields"
  label: "F-Opt-4$_{-}^{}$"
  num_eval_iters: 20
  # Parameter Configuration
  param_name: f
  param_eval_range_min: 0.05
  param_eval_range_max: 1.01
  param_eval_range_step: 0.05
  network_params:
    env_length: 200
    num_neurons: 50
#    init_value: 0.01
#    I: 0.0  # constant background input
#    J1: 0.0  # maximum excitatory connection between neurons
#    J0: 0.0  # maximum inhibitory connection between neurons
#    Iloc: 0.05  # amplitude of a place-specific input
#    f: 0.4
    nmin: 0
    nmed: 2
    nmax: 1
    disc_step: 0.5
    expected_mean_field_activity: 0.015
    mean_field_activity_remove_background: True
#    replace_neuron_attractor: False
  # Evaluation Configuration
  global_metrics:
    pos_error_mean: [ mean, min, max, std, median ]
    pos_error_std: [ mean, min, max, std, median ]
    pos_error_min: [ mean, min, max, std ]
    pos_error_max: [ mean, min, max, std ]
    pos_error_num_cat: [ mean, min, max, std, median ]
    mean_field_activity: [mean, std]
    perc_correct_fields: [mean, std]
    avg_num_fields_per_neuron: [ mean, min, max, std, median ]
    avg_num_fields_active_per_neuron: [ mean, std ]
    avg_accum_field_coverage_per_neuron: [ mean, std ]
    num_fields_total: [ mean, min, max, std, median ]
    weighted_avg_activity: [ mean, std, median ]
    num_fields_active: [ mean, std]
    activity_false_positives_num: [ mean, min, max, std, median ]
    activity_false_negatives_num: [ mean, min, max, std, median ]
    perc_unique_field_combinations: [ mean, min, max, std, median ]
  plots:
    pos_error_mean: True
    pos_error_std: False
experiment_ga:
  # Experiment Configuration
  description: "Optimization with a continuous genetic algorithm"
  num_eval_iters: 2
  # Network Configuration
  network_params:
    # f: 0.3
    num_neurons: 10
    env_length: 200
    init_value: 0.01
    prob_dead_neurons: 0.0
#    J0: 0.7
#    J1: -0.86
#    I: 0.0
#    J0: 0
#    J1: 0
    Iloc: 0.05
    expected_mean_field_activity: 0.015
    mean_field_activity_remove_background: True
#    replace_neuron_attractor: False
  # Evaluation Configuration
  global_metrics:
    pos_error_mean: [ mean, min, max, std, median ]
    pos_error_std: [ mean, min, max, std, median ]
    pos_error_min: [ mean, min, max, std ]
    pos_error_max: [ mean, min, max, std ]
    mean_field_activity: [mean]
    perc_correct_fields: [mean]
    avg_num_fields_per_neuron: [ mean, min, max, std, median ]
    num_fields_total: [ mean, min, max, std, median ]
    weighted_avg_activity: [ mean, std, median ]
  plots:
    pos_error_mean: True
    pos_error_std: False