configuration:
  population_size: 20
  selection_rate: 0.2
  mutation_prob: 0.2
  mutate_best: False
  reevaluation: False
  crossover_enabled: True
#  Possible schemes are: rank-weighting, fitness-weighting, e-greedy
  parent_selection_scheme: 'fitness-weighting'
  parent_selection_parameter: None
#  fitness_fun: '1 / (pos_error_mean + 1)'   # Only mean error
  fitness_fun: 'np.exp(-pos_error_mean*5/pos_error_max)'
#                 / 2  +  np.exp(-5*(1-perc_correct_fields)) / 2'     # Mean error + perc. correct fields

parameters:
  num_neurons:
    is_enabled: False
    min: 10
    max: 200
    step: 2
  field_ratio_threshold:
    is_enabled: False
    min: 0.75
    max: 0.95
    step: 0.01
    round_decimal: 5
  scaling_factor:
    is_enabled: False
    min: 0.1
    max: 0.5
    step: 0.05
    round_decimal: 5
  alpha:
    is_enabled: True
    min: 0.02
    max: 6.0
    step: 0.02
    round_decimal: 5
  theta:
    is_enabled: True
    min: 0.02
    max: 6.0
    step: 0.02
    round_decimal: 5
  fs_normal_mean:
    is_enabled: False
    min: 0.1
    max: 5.0
    step: 0.1
    round_decimal: 5
  fs_normal_std:
    is_enabled: False
    min: 0.05
    max: 3.0
    step: 0.05
    round_decimal: 5
  max_field_sizes:
    is_enabled: True
    min: 2
    max: 101
    step: 1
# maximum excitatory connection weight between neurons
  J1:
    is_enabled: False
    min: 0.2
    max: 1.4
    step: 0.02
    round_decimal: 5
# maximum inhibitory connection weight between neurons
  J0:
    is_enabled: False
    min: -0.4
    max: -0.02
    step: 0.02
    round_decimal: 5
  I:
    is_enabled: False
    min: 0.0
    max: 0.2
    step: 0.02
    round_decimal: 5 